[build]
  # Build command for SSR
  command = "npm run build"

  # Directory to publish (Next.js SSR build)
  publish = ".next"

  # Node.js version
  environment = { NODE_VERSION = "18" }

  # Functions directory for SSR
  functions = ".netlify/functions-internal"

[build.environment]
  # Optimize for production
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# Redirect rules for Next.js SSR
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Enable Next.js SSR on Netlify
[functions]
  directory = ".netlify/functions-internal"

# Plugin for Next.js SSR
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

# Specific headers for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for fonts
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Enable compression
[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "gzip"

# Form handling (if needed for contact form)
[forms]
  # Enable Netlify Forms
  
# Functions (if needed later)
[functions]
  directory = "netlify/functions"
